### ISSUE TITLE
Incorrect hash score calculation

### ISSUE THREAD

**Issue by apemanzilla** [1lann/krist-miner#1]
Your hash value calculation code is incorrect. You need to use the *first* six bytes of the hash - not the last six.

Here is the code that I use in my OpenCL miner to get the score of a hash:
```opencl
long hashToLong(byte* hash) {
	return hash[5] + (hash[4] << 8) + (hash[3] << 16) + ((long)hash[2] << 24) + ((long) hash[1] << 32) + ((long) hash[0] << 40);
}
```
It's been optimized as much as possible (AFAIK) while still retaining accuracy.

**Comment by 1lann** [comment]
Oh huh, I've been told wrong! Thanks for letting me know.

**Comment by apemanzilla** [comment]
No problem.
