### ISSUE TITLE
Update work fails sometimes.

### ISSUE THREAD

**Issue by bauen1** [1lann/krist-miner#2]
It just prints ```failed to update work: Get http://krist.ceriat.net/?getwork: EOF```,
Looking at what krist.ceriat.net/?work returns, there: ```65789EOF``` or there is no newline befor the end of file wich might be the issue.

**Comment by apemanzilla** [comment]
This is probably an issue that I've also encountered with the Krist server itself. Oftentimes, following a recent block submission, the database (which uses SQLite) will be temporarily locked. This produces additional warnings and errors, which are appended to the beginning of the response from the API calls, which interferes with converting it to a numerical value. I'm not sure if that is the specific issue that's causing this, but it happens with `?lastblock`, `?submitblock` and `?getwork` occasionally.

**Comment by bauen1** [comment]
So this needs an server side fix?

**Comment by 1lann** [comment]
It means that the server responded with an incomplete HTTP response. The error isn't critical unless you get it at startup because it will just continue using the last known block.

**Comment by bauen1** [comment]
Ok then :smile:
